spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/neobank_payment_db
    username: ${DB_USER:neouser}
    password: ${DB_PASSWORD:neopassword}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/neobank_payment_db
    user: ${DB_USER:neouser}
    password: ${DB_PASSWORD:neopassword}

server:
  port: 8083

logging:
  config: classpath:logback-spring.xml

neobank:
  error:
    base-url: ${ERROR_BASE_URL:https://neobank.com/errors}
