spring:
  application:
    name: ledger-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/neobank_ledger_db
    username: ${DB_USER:neouser}
    password: ${DB_PASSWORD:neopassword}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/neobank_ledger_db
    user: ${DB_USER:neouser}
    password: ${DB_PASSWORD:neopassword}

server:
  port: 8082

logging:
  config: classpath:logback-spring.xml

neobank:
  error:
    base-url: ${ERROR_BASE_URL:https://neobank.com/errors}

services:
  user-service:
    base-url: ${USER_SERVICE_URL:http://localhost:8081}

security:
  limits:
    max-transfer-amount: ${MAX_TRANSFER_AMOUNT:1000000}
    daily-spend-limit: ${DAILY_SPEND_LIMIT:5000000}
